{% set name = "idyntree" %}
{% set version = "4.2.0" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://github.com/robotology/idyntree/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 98d202817500d0440e72fff386a0d0dc94acba0e5aa25bda111be1b50ea9cf67

build:
  number: 1
  run_exports:
    - {{ pin_subpackage(name, max_pin='x') }}

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake
    - pkg-config
    - ninja
    - {{ cdt('mesa-libgl-devel') }}  # [linux]
    - {{ cdt('mesa-dri-drivers') }}  # [linux]
    - {{ cdt('libselinux') }}  # [linux]
    - {{ cdt('libxdamage') }}  # [linux]
    - {{ cdt('libxxf86vm') }}  # [linux]
    - {{ cdt('libxext') }}  # [linux]
    - {{ cdt('libxcb') }}  # [linux]
    - {{ cdt('libxfixes') }}  # [linux]
    - {{ cdt('libxau') }}  # [linux]
    - {{ cdt('expat') }}  # [linux]
    - sed  # [unix]
    - m2-sed  # [win]

  host:
    - libxml2
    - ipopt
    - eigen
    - irrlicht
    - swig
    - pip
    - build
    - python
    - cmake-build-extension
    - numpy
    - libosqp
    - osqp-eigen
    - xorg-libxfixes  # [linux]

  run:
    - python
    - {{ pin_compatible('numpy') }}
    - meshcat-python

test:
  commands:
    - test -f ${PREFIX}/include/iDynTree/KinDynComputations.h  # [not win]
    - test -f ${PREFIX}/lib/libidyntree-core.so  # [linux]
    - test -f ${PREFIX}/lib/libidyntree-core.dylib  # [osx]
    - test -f ${PREFIX}/lib/cmake/iDynTree/iDynTreeConfig.cmake  # [not win]
    - if not exist %PREFIX%\\Library\\include\\iDynTree\\KinDynComputations.h exit 1  # [win]
    - if not exist %PREFIX%\\Library\\lib\\idyntree-core.lib exit 1  # [win]
    - if not exist %PREFIX%\\Library\\bin\\idyntree-core.dll exit 1  # [win]
    - if not exist %PREFIX%\\Library\\lib\\cmake\\iDynTree\\iDynTreeConfig.cmake exit 1  # [win]
    - test $(pip list | grep idyntree | tr -s " " | grep $PKG_VERSION | wc -l) -eq 1  # [unix]
    - pip check
  imports:
    - idyntree
  requires:
    - pip

about:
  home: https://github.com/robotology/idyntree
  license: LGPL-2.1-or-later
  license_file: LICENSE.LGPL2
  summary: Multibody Dynamics Library designed for Free Floating Robots.

extra:
  recipe-maintainers:
    - traversaro
